#!/usr/bin/env python3
"""Generate src/runways_data.h from the OurAirports runways.csv.

Draws the actual paved shape of a runway on the scope, at its true position and
orientation, rather than a single dot for the whole airport.

Keeps every runway that is not closed and carries both threshold coordinates. Only
about 15k of the ~48k rows have coordinates at all; the rest are known runways with no
surveyed endpoints, and there is nothing to draw for those.

Restricted to airports that airports_data.h also carries, using the same filter, because
a runway with no marker and no ident beside it is an unidentifiable smudge - which is
exactly what showed up on screen when this took every airport in the dataset. The two
files share a membership test at generation time only; there is no index coupling at
runtime, so they cannot drift out of alignment the way parallel arrays would.

Generate both from one snapshot of the OurAirports data, or an airport added on one side
and missing on the other reintroduces the unnamed-runway bug for that field.

No length filter: a 2,000 ft GA strip is exactly the thing a local scope should show.
The renderer drops runways whose projected length is under a few pixels, which is the
right place to make that judgement because it depends on the range setting.

Usage:
    python3 tools/gen_runways.py /tmp/runways.csv src/runways_data.h /tmp/airports.csv

Source data: OurAirports (public domain). https://ourairports.com/data/
"""
import csv
import sys

SCALE = 10000.0


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/runways.csv"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/runways_data.h"
    apt = sys.argv[3] if len(sys.argv) > 3 else "/tmp/airports.csv"

    # Must mirror gen_airports.py's filter, matched on `ident` because that is what
    # runways.csv keys on (the display code is IATA for large fields and would not match).
    # gen_airports.py admits any classified airport with a surveyed runway, so the IATA
    # requirement is dropped here too -- an airport reaching this loop with runways to
    # draw is one that gets a marker. Keeping the two rules in step is what stops a strip
    # appearing with no ident beside it.
    keep = set()
    with open(apt, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            t = r["type"]
            iata = (r.get("iata_code") or "").strip().upper()
            gps = (r.get("gps_code") or "").strip().upper()
            local = (r.get("local_code") or "").strip().upper()
            if t == "large_airport":
                large = 1
            elif t in ("medium_airport", "small_airport"):
                large = 0
            else:
                continue
            code = (iata or gps or local) if large else (gps or local or iata)
            if not code[:5]:
                continue
            try:
                float(r["latitude_deg"]); float(r["longitude_deg"])
            except (ValueError, KeyError):
                continue
            ident = (r.get("ident") or "").strip().upper()
            if ident:
                keep.add(ident)

    rows = []
    with open(src, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if (r.get("closed") or "").strip() == "1":
                continue
            if (r.get("airport_ident") or "").strip().upper() not in keep:
                continue   # no marker for it, so its runways would be unlabelled
            try:
                le_lat = float(r["le_latitude_deg"])
                le_lon = float(r["le_longitude_deg"])
                he_lat = float(r["he_latitude_deg"])
                he_lon = float(r["he_longitude_deg"])
            except (ValueError, KeyError, TypeError):
                continue
            # A handful of rows carry 0,0 as a placeholder for "unknown".
            if le_lat == 0.0 and le_lon == 0.0:
                continue
            if he_lat == 0.0 and he_lon == 0.0:
                continue

            def q(v, lim):
                return max(-lim, min(lim, round(v * SCALE)))

            rows.append((q(le_lat, 900000), q(le_lon, 1800000),
                         q(he_lat, 900000), q(he_lon, 1800000)))

    with open(dst, "w") as f:
        # ASCII only: on Windows this file is written in cp1252 and an em-dash mangles.
        f.write("// Auto-generated by tools/gen_runways.py - DO NOT EDIT.\n")
        f.write("// Source: OurAirports (public domain).\n")
        f.write("// %d runways. Both thresholds as int32 deg*%d (~11 m).\n"
                % (len(rows), int(SCALE)))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define RUNWAY_SCALE %d\n" % int(SCALE))
        f.write("#define RUNWAY_NUM %d\n\n" % len(rows))

        for name, col in (("RUNWAY_LE_LAT", 0), ("RUNWAY_LE_LON", 1),
                          ("RUNWAY_HE_LAT", 2), ("RUNWAY_HE_LON", 3)):
            f.write("static const int32_t %s[RUNWAY_NUM] = {\n" % name)
            for i in range(0, len(rows), 12):
                f.write("  " + ",".join(str(r[col]) for r in rows[i:i + 12]) + ",\n")
            f.write("};\n\n")

    print("airports with markers: %d" % len(keep))
    print("runways: %d" % len(rows))
    print("flash:   ~%.1f KB" % (len(rows) * 16 / 1024.0))
    print("written: %s" % dst)


if __name__ == "__main__":
    main()
