#!/usr/bin/env python3
"""Generate src/runways_data.h from the OurAirports runways.csv.

Draws the actual paved shape of a runway on the scope, at its true position and
orientation, rather than a single dot for the whole airport.

Keeps every runway that is not closed and carries both threshold coordinates. Only
about 15k of the ~48k rows have coordinates at all; the rest are known runways with no
surveyed endpoints, and there is nothing to draw for those.

Deliberately NOT keyed to airports_data.h. Tying the two together by index would mean
regenerating both from the same snapshot every time, and the two files already disagree
by one airport because the upstream dataset moved between generations. Absolute
endpoints stand on their own and cannot drift out of alignment.

No length filter: a 2,000 ft GA strip is exactly the thing a local scope should show.
The renderer drops runways whose projected length is under a few pixels, which is the
right place to make that judgement because it depends on the range setting.

Usage:
    python3 tools/gen_runways.py /tmp/runways.csv src/runways_data.h

Source data: OurAirports (public domain). https://ourairports.com/data/
"""
import csv
import sys

SCALE = 10000.0


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/runways.csv"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/runways_data.h"

    rows = []
    with open(src, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if (r.get("closed") or "").strip() == "1":
                continue
            try:
                le_lat = float(r["le_latitude_deg"])
                le_lon = float(r["le_longitude_deg"])
                he_lat = float(r["he_latitude_deg"])
                he_lon = float(r["he_longitude_deg"])
            except (ValueError, KeyError, TypeError):
                continue
            # A handful of rows carry 0,0 as a placeholder for "unknown".
            if le_lat == 0.0 and le_lon == 0.0:
                continue
            if he_lat == 0.0 and he_lon == 0.0:
                continue

            def q(v, lim):
                return max(-lim, min(lim, round(v * SCALE)))

            rows.append((q(le_lat, 900000), q(le_lon, 1800000),
                         q(he_lat, 900000), q(he_lon, 1800000)))

    with open(dst, "w") as f:
        # ASCII only: on Windows this file is written in cp1252 and an em-dash mangles.
        f.write("// Auto-generated by tools/gen_runways.py - DO NOT EDIT.\n")
        f.write("// Source: OurAirports (public domain).\n")
        f.write("// %d runways. Both thresholds as int32 deg*%d (~11 m).\n"
                % (len(rows), int(SCALE)))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define RUNWAY_SCALE %d\n" % int(SCALE))
        f.write("#define RUNWAY_NUM %d\n\n" % len(rows))

        for name, col in (("RUNWAY_LE_LAT", 0), ("RUNWAY_LE_LON", 1),
                          ("RUNWAY_HE_LAT", 2), ("RUNWAY_HE_LON", 3)):
            f.write("static const int32_t %s[RUNWAY_NUM] = {\n" % name)
            for i in range(0, len(rows), 12):
                f.write("  " + ",".join(str(r[col]) for r in rows[i:i + 12]) + ",\n")
            f.write("};\n\n")

    print("runways: %d" % len(rows))
    print("flash:   ~%.1f KB" % (len(rows) * 16 / 1024.0))
    print("written: %s" % dst)


if __name__ == "__main__":
    main()
