#!/usr/bin/env python3
"""Generate src/airports_data.h from the OurAirports airports.csv.

Keeps every airport that carries an IATA code, all large airports, and - since runways
are drawn - anything with a surveyed runway. That last rule matters: Gardner Municipal
(K34) has two real runways and no IATA code, so the older filter drew its strips with no
marker and no ident beside them. An airport good enough to draw is good enough to name.

Requiring an IATA code is still what keeps the file from swallowing ~38,000 unnamed
strips, heliports and closed sites. Small airports are included for a reason -
OurAirports classes plenty of real, busy general-aviation fields as "small_airport"
(New Century AirCenter, KIXD/JCI, is one), and filtering by type alone silently drops
the airport nearest a lot of users.

Emits int32 lat/lon (degrees * 10000, ~11 m), a 3-letter IATA code, and a 'large'
flag. The earlier degrees*100 encoding quantised to ~1.1 km, which is invisible at a
100 km range and badly wrong for a field a few km away on a zoomed-in scope.

Pass runways.csv so the "has a runway" rule can be applied; generate airports_data.h and
runways_data.h from the same snapshot, or one file admits a field the other does not and
the unnamed-runway bug comes back for it.

Usage:
    python3 tools/gen_airports.py /tmp/airports.csv src/airports_data.h /tmp/runways.csv

Source data: OurAirports (public domain). https://ourairports.com/data/
"""
import csv
import sys

SCALE = 10000.0


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/airports.csv"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/airports_data.h"
    rwy = sys.argv[3] if len(sys.argv) > 3 else "/tmp/runways.csv"

    # Idents with at least one open runway carrying both threshold coordinates - the
    # fields whose strips actually get drawn, and which therefore need a name.
    with_rwy = set()
    try:
        with open(rwy, newline="", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                if (r.get("closed") or "").strip() == "1":
                    continue
                try:
                    a1 = float(r["le_latitude_deg"]); b1 = float(r["le_longitude_deg"])
                    a2 = float(r["he_latitude_deg"]); b2 = float(r["he_longitude_deg"])
                except (ValueError, KeyError, TypeError):
                    continue
                if (a1 == 0 and b1 == 0) or (a2 == 0 and b2 == 0):
                    continue
                i = (r.get("airport_ident") or "").strip().upper()
                if i:
                    with_rwy.add(i)
    except OSError:
        print("warning: no runways.csv - airports with runways but no IATA will be dropped")

    rows = []
    with open(src, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            t = r["type"]
            iata = (r.get("iata_code") or "").strip().upper()
            gps = (r.get("gps_code") or "").strip().upper()
            local = (r.get("local_code") or "").strip().upper()
            ident = (r.get("ident") or "").strip().upper()
            if t == "large_airport":
                large = 1
            elif t in ("medium_airport", "small_airport") and (iata or ident in with_rwy):
                large = 0
            else:
                continue

            # Label with the identifier people actually use for that kind of field.
            # Airline airports are known by IATA (MCI, not KMCI); GA fields are known by
            # their ICAO/FAA ident (KIXD, not JCI - the IATA code for New Century is one
            # almost nobody would recognise). Falls back through whatever exists.
            code = (iata or gps or local) if large else (gps or local or iata)
            code = code[:5]
            if not code:
                continue
            try:
                lat = float(r["latitude_deg"])
                lon = float(r["longitude_deg"])
            except (ValueError, KeyError):
                continue
            lat_s = max(-900000, min(900000, round(lat * SCALE)))
            lon_s = max(-1800000, min(1800000, round(lon * SCALE)))
            rows.append((lat_s, lon_s, code, large))

    # large first isn't needed; keep file order. Stats:
    n_large = sum(1 for r in rows if r[3])
    print("idents with a surveyed runway: %d" % len(with_rwy))
    with open(dst, "w") as f:
        # ASCII only: on Windows this file is written in cp1252 and an em-dash mangles.
        f.write("// Auto-generated by tools/gen_airports.py - DO NOT EDIT.\n")
        f.write("// Source: OurAirports (public domain).\n")
        f.write("// %d airports (%d large, %d medium/small). lat,lon are int32 deg*%d.\n"
                % (len(rows), n_large, len(rows) - n_large, int(SCALE)))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define AIRPORT_SCALE %d\n" % int(SCALE))
        f.write("#define AIRPORT_NUM %d\n\n" % len(rows))

        f.write("static const int32_t AIRPORT_LAT[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 12):
            f.write("  " + ",".join(str(r[0]) for r in rows[i:i + 12]) + ",\n")
        f.write("};\n\n")

        f.write("static const int32_t AIRPORT_LON[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 12):
            f.write("  " + ",".join(str(r[1]) for r in rows[i:i + 12]) + ",\n")
        f.write("};\n\n")

        f.write("// 1 = large airport (drawn as a ring), 0 = medium/small (dot).\n")
        f.write("static const uint8_t AIRPORT_LARGE[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 32):
            f.write("  " + ",".join(str(r[3]) for r in rows[i:i + 32]) + ",\n")
        f.write("};\n\n")

        f.write("// Display code: IATA for large airports, ICAO/FAA ident for the rest.\n")
        f.write("static const char AIRPORT_IATA[AIRPORT_NUM][6] = {\n")
        for i in range(0, len(rows), 10):
            f.write("  " + ",".join('"%s"' % r[2] for r in rows[i:i + 10]) + ",\n")
        f.write("};\n")

    bytes_total = len(rows) * (4 + 4 + 1 + 6)
    print("airports: %d (%d large, %d medium/small)" % (len(rows), n_large, len(rows) - n_large))
    print("flash:    ~%.1f KB" % (bytes_total / 1024.0))
    print("written:  %s" % dst)


if __name__ == "__main__":
    main()
